knccrm/knccrm/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index ,about
from userprofile.views import registrar
from django.contrib.auth import views

urlpatterns = [
    path('',index, name="index"),
    path('dashboard/lead/add-lead', include ('lead.urls')),
    path('dashboard/lead/show-lead', include ('lead.urls')),
    path('dashboard/lead/', include ('lead.urls')),
    path('dashboard/clients/', include ('client.urls')),
    path('dashboard/', include ('dashboard.urls')),
    path('about/',about, name="about"),
    path('registrar/',registrar, name="registrar"),
    path('login/', views.LoginView.as_view(template_name='userprofile/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
]

knccrm/lead/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.lead, name='lead'),
    path('add-lead/', views.add_lead, name='add_lead'),
    path('show-lead/', views.show_lead, name='show_lead'),
    path('<int:pk>/', views.lead_details, name='lead_details'),
    path('<int:pk>/edit/', views.lead_edit , name='lead_edit'),
    path('<int:pk>/delete/', views.delete_lead, name='delete_lead'),
    path('<int:pk>/convert/', views.convert_to_client, name='convert_to_client'),
    path('update/bulk/', views.update_status_priority_bulk, name='update_status_priority_bulk'),
]

knccrm/lead/models.py
from django.db import models
from django.contrib.auth.models import User



class Lead(models.Model):
    LOW='low'
    MEDIUM='medium'
    HIGH='high'
    
    LEAD_PRIORITY_CHOICES = (
        (LOW, 'Low'),
        (MEDIUM,'Medium'),
        (HIGH,'High')
        )
    
    
    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    STATUS_CHOICES = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    
    
    priority=models.CharField(max_length=10, choices=LEAD_PRIORITY_CHOICES, default='medium')
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    company = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    converted_to_clients=models.BooleanField(default=False)
    assigned_to = models.ForeignKey(User, related_name='assigned_leads', on_delete=models.SET_NULL, null=True, blank=True)
    notes = models.TextField(blank=True)
    
    
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

knccrm/lead/forms.py
from django import forms

from .models import Lead

class AddLeadForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields=('name', 'email','phone_number','company','notes','priority','status')

knccrm/lead/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from django.contrib import messages

from .forms import AddLeadForm
from .models import Lead

from client.models import Client

@login_required
def lead(request):
    return render(request, 'lead/lead.html')

@login_required
def add_lead(request):
    if request.method == "POST":
        form = AddLeadForm(request.POST)
        if form.is_valid():
            lead=form.save(commit=False)
            lead.created_by=request.user
            lead.save()
            messages.success(request, "Lead added successfully!")
            return redirect('/dashboard/')
    else:
        form=AddLeadForm()
    return render(request, 'lead/add_lead.html',{
        'form': form,
    })
    
@login_required
def show_lead(request):
    lead = Lead.objects.filter(created_by=request.user, converted_to_clients=False)
    return render(request, 'lead/show_lead.html', {
        'leads': lead
    })

    
@login_required
def lead_details(request, pk):
    lead =get_object_or_404(Lead , created_by=request.user , pk=pk)
    return render(request, 'lead/lead_details.html', {'lead': lead})

@login_required
def delete_lead(request, pk):
    lead = get_object_or_404(Lead , created_by=request.user , pk=pk)
    lead.delete()
    messages.success(request, "Lead deleted successfully!")
    return redirect('show_lead')

@login_required
def lead_edit(request , pk):
    lead = get_object_or_404(Lead , created_by=request.user , pk=pk)
    
    if request.method == "POST":
        form = AddLeadForm(request.POST, instance=lead)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "Lead updated successfully!")
            
            return redirect('show_lead')
    else:
        form= AddLeadForm(instance=lead )
        
    return render(request, 'lead/lead_edit.html',{
        'form': form,
    })
        
from django.http import JsonResponse

@login_required
def update_status_priority_bulk(request):
    if request.method == "POST":
        lead_ids = request.POST.getlist('lead_ids[]')
        priorities = request.POST.getlist('priorities[]')
        statuses = request.POST.getlist('statuses[]')
        
        for lead_id, priority, status in zip(lead_ids, priorities, statuses):
            lead = get_object_or_404(Lead, created_by=request.user, pk=lead_id)
            lead.priority = priority
            lead.status = status
            lead.save()
        messages.success(request, "Updated successfully!")
        return redirect('show_lead')
        
    return JsonResponse({'success': False})


@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    
    client = Client.objects.create(
        name=lead.name,
        email=lead.email,
        phone_number=lead.phone_number,
        company=lead.company,
        notes=lead.notes,
        created_by=request.user,
    )
    
    lead.converted_to_clients = True
    lead.save()
    
    messages.success(request, "Lead converted to client successfully!")
    
    return redirect('show_lead')

knccrm/lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}
{% block title %}Add Lead{% endblock %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl text-center font-semibold mb-8" style="color: #85754E;">ADD LEAD</h1>
    <form method="POST" action=".">
        {% csrf_token %}
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {% for field in form %}
                <div class="border border-gray-300 p-2 rounded-md">
                    <label class="block text-gray-700 mb-1">{{ field.label }}:</label>
                    {{ field }}
                    {% if field.errors %}
                        <ul class="mt-1 text-sm text-red-500">
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        
        <div class="flex justify-center mt-8">
            <button type="submit" class="py-2 px-6 text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm">Criar lead</button>
        </div>
    </form>
</div>
{% endblock %}

knccrm/lead/templates/lead/lead.html
{% extends 'core/base.html' %}
{% block title %}Leads{% endblock %}
{% block content %}
<div class="container mx-auto mt-10">
    <h1 class="text-3xl text-center font-semibold mb-8" style="color:#85754E">Leads</h1>
    <div class="flex justify-center items-center">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="p-6 bg-gray-100 rounded-lg shadow-md text-center">
                <a href="{% url 'add_lead' %}" class="btn-primary">Add Leads</a>
            </div>
            <div class="p-6 bg-gray-100 rounded-lg shadow-md text-center">
                <a href="{% url 'show_lead' %}" class="btn-primary">Show Leads</a>
            </div>
            <div class="p-6 bg-gray-100 rounded-lg shadow-md text-center">
                <label for="file-upload" class="btn-primary">Import Leads
                    <input id="file-upload" type="file" class="hidden" accept=".xml">
                </label>
            </div>
        </div>
    </div>
</div>
{% endblock %}

knccrm/lead/templates/lead/lead_details.html
{% extends 'core/base.html' %}
{% block title %}{{ lead.name }}{% endblock %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="bg-white shadow rounded-lg p-8">
        <h1 class="text-3xl font-semibold text-gray-800 mb-4">{{ lead.name }}</h1>
        {% if lead.notes %}
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Notes:</p>
            <p class="text-gray-800">{{ lead.notes }}</p>
        </div>
        {% endif %}
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Email:</p>
            <p class="text-gray-800">{{ lead.email }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Phone Number:</p>
            <p class="text-gray-800">{{ lead.phone_number }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Company:</p>
            <p class="text-gray-800">{{ lead.company }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Priority:</p>
            <p class="text-gray-800">{{ lead.get_priority_display }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Status:</p>
            <p class="text-gray-800">{{ lead.get_status_display }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Created at:</p>
            <p class="text-gray-800">{{ lead.created_at }}</p>
        </div>
        <div class="mb-6">
            <p class="text-gray-600 font-semibold">Modified at:</p>
            <p class="text-gray-800">{{ lead.modified_at }}</p>
        </div>
        <div class="flex justify-between items-center">
            <a href="{% url 'lead_edit' lead.id  %}" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 transition duration-300 ease-in-out">Edit Lead</a>
            <a href="{% url 'delete_lead' lead.id  %}" class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600 transition duration-300 ease-in-out">Delete Lead</a>
            <a href="{% url 'convert_to_client' lead.id  %}" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 transition duration-300 ease-in-out">Convert to client</a>
            <button onclick="window.location.href='{% url 'show_lead' %}'" class="bg-gray-500 text-white py-2 px-4 rounded hover:bg-gray-600 transition duration-300 ease-in-out">Back to Leads</button>
        </div>
    </div>
</div>
{% endblock %}

knccrm/lead/templates/lead/lead_edit.html
{% extends 'core/base.html' %}
{% block title %}Edit {{ lead.name }}{% endblock %}
{% block content %}
<div class="py-6 px-6">
    <h1 class="text-3xl text-center font-semibold mb-8" style="color: #85754E;">Editar lead</h1>
    <form method="POST" action=".">
        {% csrf_token %}

        <div style="display: grid; grid-template-columns: repeat(1, minmax(0, 1fr)); gap: 1rem;">
            {% for field in form %}
                <div style="border: 1px solid #E5E7EB; border-radius: 0.375rem;">
                    <label class="block text-gray-700 mb-1">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                                <li style="color: red;">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div style="display: flex; justify-content: center; margin-top: 1rem;">
            <button style="padding: 0.75rem 1.5rem; background-color: #85754E; color: white; border: none; border-radius: 9999px; cursor: pointer; transition: background-color 0.3s ease-in-out;" type="submit">Guardar lead</button>
        </div>
</form>
</div>

{% endblock %}

knccrm/lead/templates/lead/show_lead.html
{% extends 'core/base.html' %}
{% block title %}Show Leads{% endblock %}
{% block content %}
<div class="py-6 px-6">
    <h1 class="text-3xl text-center font-semibold mb-8" style="color: #85754E">Leads</h1>

    <div class="grid grid-cols-7 gap-4 text-center mb-4" style="background-color: #F3F4F6; color: #4B5563; border-radius: 8px; padding: 10px;">
        <p class="font-semibold"><a href="?sort=name">Name</a></p>
        <p class="font-semibold"><a href="?sort=email">Email</a></p>
        <p class="font-semibold"><a href="?sort=phone_number">Phone Number</a></p>
        <p class="font-semibold"><a href="?sort=company">Company</a></p>
        <p class="font-semibold">Notes</p>
        <p class="font-semibold">Priority</p>
        <p class="font-semibold">Status</p>
    </div>

    <form method="POST" action="{% url 'update_status_priority_bulk' %}">
        {% csrf_token %}
        {% for lead in leads %}
        <div class="grid grid-cols-7 gap-4 text-center mb-4" style="background-color: #FFFFFF; color: #111827; border-radius: 8px; padding: 10px;">
            <p>
                <a href="{% url 'lead_details' lead.id %}">{{ lead.name }}</a>
            </p>
            <p>{{ lead.email }}</p>
            <p>{{ lead.phone_number }}</p>
            <p>{{ lead.company }}</p>
            <p>{{ lead.notes }}</p>
            <input type="hidden" name="lead_ids[]" value="{{ lead.id }}">
            <p>
                <select name="priorities[]">
                    {% for priority_choice in lead.LEAD_PRIORITY_CHOICES %}
                    <option value="{{ priority_choice.0 }}" {% if lead.priority == priority_choice.0 %}selected{% endif %}>{{ priority_choice.1 }}</option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <select name="statuses[]">
                    {% for status_choice in lead.STATUS_CHOICES %}
                    <option value="{{ status_choice.0 }}" {% if lead.status == status_choice.0 %}selected{% endif %}>{{ status_choice.1 }}</option>
                    {% endfor %}
                </select>
            </p>
        </div>
        {% empty %}
        <p>empty</p>
        {% endfor %}
        <div class="text-center mt-4">
            <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Save Changes</button>
        </div>
    </form>

</div>
{% endblock %}